### PR TITLE
Fix delegation reducer

### PR DESCRIPTION
**Pull request by lukitsbrian**

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Great! Thank you

Before:

image


After:

image

**Comment by Bitcoinera** [comment]
Actually `coinReducer` should work though. Seems precision is messed up again?

**Comment by Bitcoinera** [comment]
Ah, OK, I see. `balance` is actually `amount` in `delegations`. Cool.

Thank you again :pray:

**Comment by faboweb** [comment]
I don't get this fix, can someone explain?

**Comment by Bitcoinera** [comment]
> I don't get this fix, can someone explain?

`balance` wasn't balance at all :shrug: then it wasn't finding any `coinLookup` in `coinReducer` and therefore sending the amount as it was

**Comment by faboweb** [comment]
If balance wasn't balance, what changed?

**Comment by Bitcoinera** [comment]
> If balance wasn't balance, what changed?

It changed that now we are calculating amount and denom separately. Amount will be calculated with the getStakingViewAmount function.

Actually `coinReducer` is not needed. Now I am seeing that

**Pull request merged**
