### PR TITLE
Ana/281 proposal status missing important data

### LINKED ISSUE #281: proposal status is missing important data
Screen Shot 2020-11-25 at 11 57 02 AM

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #281

Like this @jbibla ? Or better hide the `Entered...` when it is a Rejected / Passed proposal?

image

### CODE REVIEW

**Comment by jbibla** [comment]
nice! yeah, hide `entered`

just `rejected 5 days ago`

probably hide the bar? unless it has data that makes sense.

**Comment by Bitcoinera** [comment]
> probably hide the bar? unless it has data that makes sense.

I shows that Yes === No Votes, in thise case 0... But yeah, I will hide it for 0 values :+1:  Otherwise a bit confusing

**Comment by Bitcoinera** [comment]
This is how it is looking now:

image

**Comment by jbibla** [comment]
sorry, why are the votes displaying if there 0 votes?

**Comment by Bitcoinera** [comment]
> sorry, why are the votes displaying if there 0 votes?

Well, I can also hide that one, yes

**Comment by Bitcoinera** [comment]
Mmm, it doesn't look so nice actually, hiding it

image

And showing 0 Votes also gives some info. It actually shows that nobody voted. Gives more information than hiding it

**Review by jbibla — APPROVED** [review]

**Pull request merged**
