### PR TITLE
Fabo/keplr

### PR DESCRIPTION
**Pull request by faboweb**
Working sign in (automatic if available) and signing

image
image

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Let's try this!

**Comment by Bitcoinera** [comment]
image

I get this with no accounts in keplr. Probably we also should handle this case, right?

**Comment by Bitcoinera** [comment]
OK, I will debug. I tried both Brave and Chrome and with account and it is not loading. Linux??

image

**Comment by faboweb** [comment]
Lol, chainId was removed on purpose as discussed....

**Comment by faboweb** [comment]
Instead of moving the error and loading around: why is loading not set to false?

**Comment by Bitcoinera** [comment]
> Lol, chainId was removed on purpose as discussed....

Ah true true. OK, we need it for Keplr. It was broken

**Comment by Bitcoinera** [comment]
I couldn't try this fully yet since I found another important bug in Lunie Light related to our loading logic that prevented me to try anything. Will open an issue on this asap

**Comment by faboweb** [comment]
> > Lol, chainId was removed on purpose as discussed....
> 
> Ah true true. OK, we need it for Keplr. It was broken

We don't need to hard code it. Whenever we need it, we can just load a block and extract it. This is the case here. What is broken exactly?

**Comment by Bitcoinera** [comment]
> We don't need to hard code it. Whenever we need it, we can just load a block and extract it. This is the case here. 

OK, fixed. You were right. Just using block as it is best

**Comment by Bitcoinera** [comment]
Nice

**Pull request merged**
